### ISSUE TITLE
Using rosnodejs.nh vs rosnodejs.initNode

### ISSUE THREAD

**Issue by renatosamperio** [RethinkRobotics-opensource/rosnodejs#116]
Hi,

I was trying to understand the following code from your README file:

`const nh = rosnodejs.nh;`
`const sub = nh.subscribe('/chatter', 'std_msgs/String', (msg) => {`
`  console.log('Got msg on chatter: %j', msg);`
`});`

But is ending not defining the node handler itself and in an error (NodeHandle.js:134). Shall I always use the **rosnodejs.initNode** way?

Regards,

Renato.

**Comment by chfritz** [comment]
Yes, you always need to init the node first. Without it you are not connected to roscore. We should probably clarify this in the README.

**Comment by renatosamperio** [comment]
Thanks. It works quite nice.
