### ISSUE TITLE
Adding syslog logger

### ISSUE THREAD

**Issue by renatosamperio** [RethinkRobotics-opensource/rosnodejs#122]
What would be the best way to include more loggers into **rosnodejs**? As in rospy (logging) and roscpp (log4cxx), we would like to keep adding existing loggers such like syslog ([bunyan-syslog](https://github.com/joyent/node-bunyan-syslog)) or customised ones.

**Comment by chris-smith** [comment]
rosnodejs loggers are just thin wrappers around bunyan loggers, so you can add bunyan streams to them. You should be able to add them to a logger directly or at initialization.

```
const myLogger = rosnodejs.log.getLogger('myLogger');
myLogger.addStream({ ... });
// OR
rosnodejs.initNode('my_node', { logging: { streams: [ ... ] }});
```

**Comment by chris-smith** [comment]
Assuming this is resolved.
