### ISSUE TITLE
Improvement: Rostopic list command

### ISSUE THREAD

**Issue by 808brick** [RethinkRobotics-opensource/rosnodejs#124]
Is there currently or any future plans to have a function to return the list of rostopics that are available?

This was the work around I had to do to accomplish this, but I was wondering if there was an easier way?
```javascript
const exec = require('child_process').exec

function rostopic_list(callback){
  exec("rostopic list", (err, stdout, stderr) => {
    var res = stdout.split("\n");
    res.splice(-1,1);
    callback(res);
})
}
```
Which I then retrieve the value from by doing
```javascript
var list = rostopic_list(function (result) {
    return result;
  });
```

**Comment by chris-smith** [comment]
You can use [`NodeHandle.getSystemState()`](http://wiki.ros.org/ROS/Master_API#Name_service_and_system_state) to get the information for `rostopic list`, though the format of the response is not the same - `rostopic list` is most likely using `getSystemState()`.
