### ISSUE TITLE
Is this being maintained post-shutdown?

### ISSUE THREAD

**Issue by dheera** [RethinkRobotics-opensource/rosnodejs#125]
I'm currently using rosnodejs in a number of nodes, but is there someone who is taking charge of maintaining rosnodejs after the Rethink shutdown?

**Comment by chris-smith** [comment]
I'm continuing to maintain rosnodejs. I don't have any plans to stop, but am happy for help if there's updates people are looking for - I haven't seen much in the way of requests so it's been relatively quiet.

**Comment by dheera** [comment]
This @chris-smith for maintaining this! Are there plans for an "official" ROS 2 version?

**Comment by chris-smith** [comment]
@minggangw and Intel already have one over [here](https://github.com/RobotWebTools/rclnodejs)!

**Comment by dheera** [comment]
Thanks!
