### ISSUE TITLE
can't install because of chfritz/node-xmlrpc

### ISSUE THREAD

**Issue by ValeryVS** [RethinkRobotics-opensource/rosnodejs#127]
`chfritz/node-xmlrpc` dependency can not be installed without ssh access using node>=8
For me `npm install` hanged.
Can you publish `node-xmlrpc` or set dependency explicitly with https protocol?

**Comment by chris-smith** [comment]
Do you explicitly _not_ have ssh access for some reason? Does this resolve your issue https://docs.npmjs.com/common-errors#npm-only-uses-git-and-sshgit-urls-for-github-repos-breaking-proxies?

**Comment by ValeryVS** [comment]
Yes, I haven't.
I definitely solve this with `git config url."https://".insteadOf git://`, but this workaround is quite hacky.

I wont use https every time, so `url."https://".insteadOf` should be set before every `npm install`, and deleted after every `npm install`. I know, this can be done with `preinstall` and `postinstall` scripts with npm>=5. And node@6, where `preinstall` is broken in npm@3, use https by default.

If new xmlrpc package could be published, it would be much easier.
