### ISSUE TITLE
UTF-8 multi-byte character serialization broken in 3.0.0

### ISSUE THREAD

**Issue by mvollrath** [RethinkRobotics-opensource/rosnodejs#132]
I'm working on a project using rosnodejs and non-English languages and have come across a silent data loss issue when serializing strings containing multi-byte UTF-8 characters.

This issue is fixed in kinetic-devel, but it has not been released yet.  A 3.0.1 release with the UTF-8 fixes would be greatly appreciated!

**Comment by mvollrath** [comment]
I've opened https://github.com/RethinkRobotics-opensource/gennodejs/pull/19 to fix this in gennodejs as well.

**Comment by chris-smith** [comment]
sure can do - I'll probably wait for releasing until the fix in `gennodejs` is merged and I can add some unicode tests here.

**Comment by mvollrath** [comment]
> sure can do - I'll probably wait for releasing until the fix in `gennodejs` is merged and I can add some unicode tests here.

I've opened #133 with a UTF-8 string test that fails on 3.0.0 and passes on kinetic-devel.

**Comment by mvollrath** [comment]
@chris-smith anything else I can do to help make this release?

**Comment by chris-smith** [comment]
Nope! Sorry about the delay - doing it now.

**Comment by chris-smith** [comment]
3.0.1 should be up - not sure when an official `gennodejs` release can happen, but including it in overlays should work until then (or using `rosnodejs` messages)

**Comment by mvollrath** [comment]
Thank you :tada:
