### ISSUE TITLE
Unify API for on-the-fly generated and pre-compiled message classed

### ISSUE THREAD

**Issue by chfritz** [RethinkRobotics-opensource/rosnodejs#14]
See https://github.com/RethinkRobotics-opensource/rosnodejs/pull/12#issuecomment-219899631.

This is complicated slightly by the fact that pre-compiled message classes can be instantiated synchronously, whereas on-the-fly generation of message classes is asynchronous. So a unified interface may need to follow the asynchronous approach, i.e., use a callback rather than a return value.

**Comment by chris-smith** [comment]
If you promisify on-the-fly message generation (or at least part of it), you could do the asynchronous generation in `rosnodejs.init` e.g.

```
rosnodejs.init('/my_node', {messages: ['std_msgs/String'], services: ['std_srvs/SetBool']})
.then(...)
```

I think the messages should probably be generated before we start checking for the master. So where we create a new promise in the init function, if users provided messages and services in the options, you would instead do

```
init() {
  ...
  return this.use(options.messages, options.services)
  .then(() => {
    _checkMasterHelper(resolve, 0);
  }
}
```

**Comment by chfritz** [comment]
That sounds good!

**Comment by chfritz** [comment]
OK, PR created.
