### ISSUE TITLE
Bad tag reference from noetic release (ros gbp) and upstream (this repo)

### ISSUE THREAD

**Issue by kunaltyagi** [RethinkRobotics-opensource/rosnodejs#166]
Steps to reproduce and error output
```
$ rosinstall_generator perception --rosdistro noetic --deps --upstream  > perception.rosinstall
$ vcs import --input perception.rosinstall ./src/
=== ./src/noetic/gennodejs (git) ===
Could not checkout ref '2.0.2': fatal: invalid reference: 2.0.2
```

Solution:
* Add the 2.0.2 tag at the correct commit
* Release a new version for noetic with the correct tag

**Comment by chris-smith** [comment]
This would seem to be an issue with [gennodejs](https://github.com/RethinkRobotics-opensource/gennodejs) so I'd recommend re-opening this there.
