### ISSUE TITLE
Can rosnodejs be used for mobile ROS applications?

### ISSUE THREAD

**Issue by bofetadas** [RethinkRobotics-opensource/rosnodejs#174]
Hi,

I want to develop a React Native app that is able to communicate with a ROS network. In fact, this is going to be the only purpose of the app. That is, it will not connect to the internet, a database or a backend service other than the ROS network itself. I want to use React Native as it allows me to simultaneously develop for Android and iOS which saves me a lot of time. 

Now I wonder if I can use rosnodejs for the ROS communication together with React Native? I know that I could use roslibjs but I'd like to know if that was also possible with rosnodejs.

Regards, Max

**Comment by chris-smith** [comment]
Unfortunately I don't know anything about React Native - assuming you'd have access to all node.js modules, I'm not sure why it wouldn't work. We do need raw tcp sockets while roslibjs just uses websockets.
