### ISSUE TITLE
Is it possible to receive message without deserialize?

### ISSUE THREAD

**Issue by lantica** [RethinkRobotics-opensource/rosnodejs#175]
I'd like to subscribe to a topic to serve as health checking.
However, the message being published is quite large and it leads to a high usage of CPU during deserialization of message which the content of the message doesn't matter to me.

Is there any way to receive the message without deserialization?

**Comment by chris-smith** [comment]
You could hack your way around to it. [This](https://github.com/RethinkRobotics-opensource/rosnodejs/blob/kinetic-devel/src/lib/impl/SubscriberImpl.js#L482) is where we attach the event listener that leads to deserialization. You could remove the listener we attach and add your own. There's one of these per publisher connection.

Though if you have access, I'd recommend just adding another topic you can subscribe to.

**Comment by lantica** [comment]
Thank you for the advice. I can add my on event listener on it now.

However, the cpu usage does not reduce even it does not deserialize the message.
Could you suggest some other possibilities causing the high cpu usage?
The message type of the topic I subscribing to is PointCloud2.

**Comment by chris-smith** [comment]
The only other thing I can think of is just from pulling the messages off the wire - that happens [here](https://github.com/RethinkRobotics-opensource/rosnodejs/blob/kinetic-devel/src/utils/serialization_utils.js#L58). PointCloud messages are generally pretty big and we don't reuse buffers so it could cause a lot of memory allocation.

**Comment by chfritz** [comment]
That issue seems to be recurring, and reusing buffers was also suggested here: https://github.com/RethinkRobotics-opensource/rosnodejs/issues/118#issuecomment-639252354. Seems like a good idea.
