### ISSUE TITLE
How to registry a new msg. How to subscribe custom messages? I need help!

### ISSUE THREAD

**Issue by f-y-l** [RethinkRobotics-opensource/rosnodejs#178]
my.js
```
const gui_msgs = rosnodejs.require('gui_msgs').msg;
let sub2 = rosNode.subscribe('/mode_cmd', gui_msgs.mode_cmd,
    (data) => { // define callback execution
        rosnodejs.log.info('I heard /mode_cmd: [' + data + ']');
    }
);
```
rosnodejs>dist>utils>messageGeneration>messages.js
```
// Registry

var registry = {
  'gui_msgs':{
    msg:{
      'mode_cmd':{
        'header':"Header",
        'mode':"int32"
      }
    },
    srv:{
      Request:{},
      Response:{}
    }
  }
};
/*
   registry looks like:
  { 'packagename':
    {
      msg: {
        'String': classdef,
        'Pose': classdef,
        ...
      },
      srv: { Request:
             {
               'SetBool': classdef,
               ...
             },
             Response:
             {
               'SetBool': classdef,
               ...
             }
           }
    },
    'packagename2': {..}
  };
*/
```
rosbagmsg:
![Selection_025](https://user-images.githubusercontent.com/39905436/122731550-ffef9a80-d2ad-11eb-9bf3-11be89e8339f.png)
error:
![Selection_026](https://user-images.githubusercontent.com/39905436/122732077-7d1b0f80-d2ae-11eb-8f82-c87fc30d1a11.png)
![Selection_027](https://user-images.githubusercontent.com/39905436/122743508-a0978780-d2b9-11eb-93db-97679e3c3838.png)

**Comment by chfritz** [comment]
which message generation are you using? [`onTheFly`](https://github.com/RethinkRobotics-opensource/rosnodejs/blob/kinetic-devel/src/examples/on_the_fly.js#L5) or the default, provided by gennodejs?

**Comment by f-y-l** [comment]
Thank you for your answer. I created a new MSG in my workspace. After compiling, it can be solved by running

**Comment by chengchenglee** [comment]
@f-y-l 
I am facing the same problem could you please provide more details about the solution?
