### ISSUE TITLE
How to import rosnodejs libraries using imort

### ISSUE THREAD

**Issue by desstiony** [RethinkRobotics-opensource/rosnodejs#182]
Hello, I'm using vue3 and don't support require to introduce libraries, how can I use import to import rosnodejs libraries

**Comment by QuentinLB** [comment]
This package is not setup to work in a browser, only for Node in a backend environnement. To use with Vue maybe try to use https://github.com/RobotWebTools/roslibjs instead.

**Comment by desstiony** [comment]
ok, thinks
