### ISSUE TITLE
Requesting non available gennodejs file

### ISSUE THREAD

**Issue by CommonParrot** [RethinkRobotics-opensource/rosnodejs#184]
I want to use the autoware-msgs msg types in my project, and because of that I installed the ros-noetic-autoware-msgs package that is built from the newest version of: https://github.com/Autoware-AI/messages/tree/master/autoware_msgs.
But when rosnodejs tries to subscribe to a autoware-msgs topic, it tries to find a CameraExtrinsic.js in the gennodejs folders.
The problem with that is that the CMakeLists.txt in the autoware repo does not include CameraExtrinsic and that is why there is no js file generated for it. Despite of CameraExtrinsic.msg being a file inside of the repo linked above, it is not installed as a message type normally.
Is there a way around downloading the project from Github and building/installing it manually with catkin and a changed CMakeLists file that includes CameraExtrinsic? By changing which message types rosnodejs expects specifically perhaps?

**Comment by chfritz** [comment]
You can avoid the need for gennodejs entirely if you use the `onTheFly` option. When you use that, message definitions will be loaded and compiled when `required` in your program. For that they just need to be in the `CMAKE_PREFIX_PATH` that is set by ROS's `setup.bash`, and which you can append to as needed.

Our example for this is here:
https://github.com/RethinkRobotics-opensource/rosnodejs/blob/4aeb3c9689658609851d728b382da1b86c85f089/src/examples/on_the_fly.js#L5

**Comment by CommonParrot** [comment]
Thank you, this avoids the error. But for some reason my performance gets considerably worse. I just switched between true and false a few times and the video footage, for example, goes from smooth to really stuttery.

**Comment by chfritz** [comment]
ah, yes, there is still an issue with large messages in the onTheFly approach, see https://github.com/RethinkRobotics-opensource/rosnodejs/issues/118#issuecomment-640881706. This shouldn't be too hard to fix, but I haven't found the time yet. For you this means that it might indeed be easier to just copy your msg files into your catkin workspace and make sure they get build (run through gennodejs) by adding them to your `CMakeLists.txt` under the `add_message_files` section.

**Comment by CommonParrot** [comment]
Ok, I will look into it for a bit and read into the project. If that results in too much effort I will build the package myself.
Thank you again for your help! I'll close the issue because onTheFly is the solution in principle.
