### ISSUE TITLE
Ros with Nodejs backend

### ISSUE THREAD

**Issue by XavierJDN** [RethinkRobotics-opensource/rosnodejs#201]
I want to create a backend server that communicate with a ros robot. I want to use ros in my backend and not a rosbridge_suite package

**Comment by chfritz** [comment]
Well, then I think you've come to the right place. That's what rosnodejs (and for ros2, rclnodejs) is for.

**Comment by XavierJDN** [comment]
ok thanks

**Comment by chfritz** [comment]
@chris-smith I think this can be closed.

**Comment by XavierJDN** [comment]
yes @chfritz
