### ISSUE TITLE
Backticks in msg definition comments result in invalid JS syntax

### ISSUE THREAD

**Issue by chfritz** [RethinkRobotics-opensource/rosnodejs#204]
In working with a user of [Transitive](https://github.com/transitiverobotics/transitive), I discovered that backticks in comments in `.msg` files result in auto-generated JS code that is invalid (the included backticks end the multi-line string we generated that itself uses backticks as delimiter). Unfortunately, there are even official ROS packages like [GridMap](https://docs.ros.org/en/jade/api/grid_map_msgs/html/msg/GridMap.html) that use backticks in their comments.

The resulting error when trying to load those files is (here for GridMapInfo):
```
[2024-10-18T22:44:40.681Z main error] **** Caught exception: SyntaxError: Unexpected identifier 'header': /opt/ros/noetic/share/gennodejs/ros/grid_map_msgs/msg/GridMapInfo.js:126
    # Pose of the grid map center in the frame defined in `header` [m].
                                                           ^^^^^^

SyntaxError: Unexpected identifier 'header'
```

The good news is that it is easy to fix, and I already have a fix ready [here](https://github.com/chfritz/rosjs/commit/7fa86b859142f9766ca962f2e0e9a89b98c4f506).

@chris-smith I'm not certain how gennodejs works these days. Is it still using [this completely separate python implementation](https://github.com/RethinkRobotics-opensource/gennodejs/blob/kinetic-devel/src/gennodejs/generate.py) or does it use the message generation from this repo by now? If the latter, then the above fixes would be easy to apply. If it's a completely separate implemetation in Python we would need to fix it there, too.

I'll create a PR for the node.js version for now.

**Comment by chris-smith** [comment]
`gennodejs` is still a separate python implementation, though we're using [`genmsg`](https://github.com/RethinkRobotics-opensource/gennodejs/blob/kinetic-devel/src/gennodejs/generate.py#L706) there so might not have to do anything?

**Comment by chfritz** [comment]
hm, then it seems genmsg has the same bug. Because if you install `ros-noetic-grid-map-msgs` from the apt repo and check, you'll see that the included `.js` file is invalid:
```
🞂 node -c /opt/ros/noetic/share/gennodejs/ros/grid_map_msgs/msg/GridMap.js
/opt/ros/noetic/share/gennodejs/ros/grid_map_msgs/msg/GridMap.js:150
    # determine which layers from `layers` need to be valid
                                   ^^^^^^

SyntaxError: Unexpected identifier 'layers'
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at checkSyntax (node:internal/main/check_syntax:78:3)

Node.js v20.18.0
```

**Comment by chris-smith** [comment]
hmm actually it probably is just `gennodejs`? In `genpy` or `gencpp` they presumably aren't using backticks so not escaping them is fine.

**Comment by chfritz** [comment]
In that case we can probably just sanitize the result we get from `genmsg.compute_full_text`?

**Comment by chris-smith** [comment]
sounds right to me
