### ISSUE TITLE
Subscribing to message types not in std_msgs

### ISSUE THREAD

**Issue by emielsteerneman** [RethinkRobotics-opensource/rosnodejs#67]
I'm trying to include rosnodejs into a project, which uses messages that are not in 'std_msgs'. These messages are defined in our own packages. I want to subscribe to these custom messages, but I cannot find a way to do so. Plugging in std_msgs.msg.String gives me the following error : 

"[ERROR] [1504707499.036] (ros.rosnodejs): Client [/jsNode] wants topic /robotcommands to have datatype/md5sum [std_msgs/String/992ce8a1687cec8c8bd883ec73ca41d1], but our version has [myproject_msgs/RobotCommand/bd4e3fb1e84585feac0a9174a19b71be]. Dropping connection.
"

code : 
_let ros = require('rosnodejs');
let std_msgs = ros.require('std_msgs')
ros.initNode('/jsNode')
.then((rosNode) => {
  rosNode.subscribe('/robotcommands', std_msgs.msg.String,  msg => {
  	console.log(msg)
  })
})_
Is there a way to describe to these messages?

**Comment by emielsteerneman** [comment]
By accident, I figured out how to do this using the function require('rosnodejs').getAvailableMessagePackages(). Apparently, my messages are defined in workspace/devel/share/gennodejs/ros/myproject_msgs/_index.js

**Comment by chris-smith** [comment]
The [wiki](http://wiki.ros.org/rosnodejs/overview/messages) has more information about generating messages if you need it.
