### ISSUE TITLE
Node.js client of ROS 2.0

### ISSUE THREAD

**Issue by minggangw** [RethinkRobotics-opensource/rosnodejs#77]
Hi @chris-smith,

This is Minggang from Open Source Technology Center, Intel. I am very glad to meet you on Github:smile:, we just implemented [rclnodejs](https://github.com/RobotWebTools/rclnodejs), a Node.js client of ROS2.0, which has the same functions as you did in ROS 1.0, but for the next generation.

My section focuses on promoting the web technology to different fields, like robotics. So I think we can collaborate if possible, especially to escalate the influence of Node.js ecosystem in ROS. As web has  built-in advantage in cross-platform and visualization and easy to develop, we want to use JavaScript to facilitate the development of ROS apps. Meanwhile, we hope to leverage platform, like [NW.js](https://github.com/nwjs/nw.js) and modules of RWT to make some wonderful usages in ROS2.0 to show the capabilities of web and improve its status in ROS.

Thanks!

**Comment by chris-smith** [comment]
Hey @minggangw! We've been keeping an eye on the progress with `rclnodejs` and were happy to see it get picked up so early! I definitely think there's a lot we can do to help push Node.js and ROS more in the community - lots of tools that could reasonably be shared across JS runtimes too.
