### ISSUE TITLE
[ERROR] [1512132643.557] (ros.rosnodejs): Exception trying to subscribe to topic /chatter

### ISSUE THREAD

**Issue by rajnunes** [RethinkRobotics-opensource/rosnodejs#79]
@IanTheEngineer Ive tried executing the same code that is available and I'm getting  this error.

at one point i got an error saying that the package std_msgs was not defined, I've also tried reinstalling rosnodejs and npm just incase there were any problems while installing 

Ive made a few changes so that i could debug ive attached the code below
[forceFeedback.js.tar.gz](https://github.com/RethinkRobotics-opensource/rosnodejs/files/1521646/forceFeedback.js.tar.gz)

**Comment by chris-smith** [comment]
What is the exception you're seeing? Is it different than the `std_msgs` one? What code that's available are you referring to?

Also - `rosnodejs` version, ROS version, OS, how are you generating messages?

**Comment by chris-smith** [comment]
From the current information this doesn't seem like a bug so I'm closing for now - feel free to re-open if you're still experiencing the issue or think otherwise.
