### ISSUE TITLE
ImageTransport - Getting images from /image_raw topic?

### ISSUE THREAD

**Issue by shreks7** [RethinkRobotics-opensource/rosnodejs#83]
Is it possible to get the image stream from ROS like rospy does it?

**Comment by chris-smith** [comment]
What do you mean by "like rospy"? Provided you have the message definitions you should be able to subscribe to anything.

**Comment by shreks7** [comment]
Got it ! I meant so that I can pass it over to node-opencv and process it like rospy. 
For someone who is try to do this - sensor_msgs.msg.Image works !

Thank you !

**Comment by 808brick** [comment]
@shreks7 Can you elaborate on how you used node-opencv to process the messages into view-able images?
