### ISSUE TITLE
Timestamp specification in ActionClient's cancel

### ISSUE THREAD

**Issue by jstnhuang** [RethinkRobotics-opensource/rosnodejs#99]
According to 2x2 matrix in http://wiki.ros.org/actionlib/DetailedDescription#The_Messages, the meaning of a cancellation message varies based on goal ID and the timestamp. Currently, ActionClientInterface's `cancel` always sets the timestamp to the current time. So there is no way to cancel all goals if some goals have a timestamp in the future.

I realize that's a an uncommon use case, but it seems like a good idea to try to match the documentation as closely as possible. Perhaps we could change `cancel(goalId)` to `cancel(goalId, stamp)`. If `stamp` is undefined, then set it to the current time, so the behavior is unchanged for existing users.

It would also be nice to have an unambiguous `cancelAllGoals()`, which is a convenience function for `cancel()`. Both the Python and C++ action clients have a `cancelAllGoals` method.

Thoughts?

**Comment by chris-smith** [comment]
This definitely makes sense to do! I'm not necessarily sure whether this is something `ActionClientInterface` should expose vs a more to-spec `ActionClient` class, but full action support will likely imply breaking changes at some point anyway...

I have a fair amount of work done to provide more action support, but I can't guarantee when it will be in a place to merge in. It may make the most sense for me to just push it to another branch for now and then people can experiment and do action-related work there while things shake out?

**Comment by chris-smith** [comment]
To clarify, I've been slowly working on this [branch](https://github.com/RethinkRobotics-opensource/rosnodejs/compare/actions). I assume very little of it actually works at this point. It may make sense to work on action support there for a bit and then we can merge that branch into kinetic-devel?

**Comment by chris-smith** [comment]
@jstnhuang - I think this should be resolved by #110 ?
